extends: airbnb
parser: babel-eslint
env:
  node: true
  es6: true
  mocha: true
rules:
  no-unused-vars:
  - error
  - varsIgnorePattern: should|expect
  valid-jsdoc:
  - error
  - requireReturn: true
    requireReturnType: true
    requireParamDescription: true
    requireReturnDescription: true
  require-jsdoc:
  - error
  - require:
      FunctionDeclaration: true
      MethodDefinition: true
      ClassDeclaration: true
